# Name of website
title: SAW's escape room

# Your name to show in the footer
author: Francesco Rombaldoni

###############################################
# --- List of links in the navigation bar --- #
###############################################

# Registrazione delle collections in un unico blocco
collections:
  storia:
    output: true
    permalink: /storia/:path/
  punteggi:
    output: true
    permalink: /punteggi/:name/

# Navbar links: uso una forma esplicita a mappa (va bene) oppure
# puoi usare una lista di coppie se preferisci compatibilit√† con alcuni template.
navbar-links:
  Informazioni: "aboutus"
  Storia: "storia"
  Risorse:
    - GitHub: "https://github.com/R0mb0/Saw_2-Inspired_Escape_Room"
  #Author's home: "Author's url site"

################
# --- Logo --- #
################

avatar: "/assets/img/Logo.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "f.rombaldoni@campus.uniurb.it"
  github: Pomodoro-Musei-di-Pesaro

rss-description: SAW's escape room

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true

url-pretty: "https://github.com/R0mb0/Saw_2-Inspired_Escape_Room"

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

navbar-col: "#590202"
navbar-text-col: "#BF364F"
navbar-border-col: "#590202"
page-col: "#1A1B20"
text-col: "#BF364F"
link-col: "#008AFF"
hover-col: "#BF5E66"
footer-col: "#590202"
footer-text-col: "#BF364F"
footer-link-col: "#BF364F"
footer-hover-col: "#BF5E66"

#################################
# --- Web Analytics Section --- #
#################################

####################
# --- Comments --- #
####################

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# Escludi questi file dalla build
exclude:
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
